### ISSUE TITLE
Installed but cannot import

### ISSUE THREAD

**Issue by jingweiz** [Farama-Foundation/ViZDoom#340]
Hey,
* System configuration: `Ubuntu16.04`, `anaconda3`, `python3.6`
* Output of `pip install vizdoom`:
```
Requirement already satisfied: vizdoom in~/anaconda3/envs/doom-env/lib/python3.6/site-packages (1.1.6)
Requirement already satisfied: numpy in ~/anaconda3/envs/doom-env/lib/python3.6/site-packages (from vizdoom) (1.15.1)
```
* `$ ls ~/anaconda3/envs/doom-env/lib/python3.6/site-packages/ | grep doom`:
```
vizdoom-1.1.6.dist-info
```
* try to import:
```
$ python
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import vizdoom
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'vizdoom'
```

I guess if it is installed successfully then inside `~/anaconda3/envs/doom-env/lib/python3.6/site-packages/` there should be another `vizdoom` folder besides the `vizdoom-1.1.6.dist-info` folder?
Any help would be highly appreciated! Thanks in advance!

**Comment by Miffyli** [comment]
Sadly this is an ongoing issue (see #311 ) and I do not know is this has been fixed yet.

@mwydmuch ?

**Comment by JaydenTaylor** [comment]
I had the same issue, I made a new virtual environment and re-installed vizdoom and it worked fine.

**Comment by ionvision** [comment]
> I had the same issue, I made a new virtual environment and re-installed vizdoom and it worked fine.

I also created a new virtual environment in Anaconda but still failed to import. Could you share a bit more details of the setup procedure? Thanks!

**Comment by mwydmuch** [comment]
The building system has been updated since then, manylinux wheels are now provided, closing the issue.
